# Copyright (c) 2020, salesforce.com, inc.
# All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
# For full license text, see the LICENSE file in the repo root
# or https://opensource.org/licenses/BSD-3-Clause

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ner.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="ner.proto",
    package="",
    syntax="proto3",
    serialized_options=None,
    serialized_pb=_b(
        '\n\tner.proto"\xa5\x01\n\x14NERPredictionRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x10\n\x08\x64ocument\x18\x02 \x01(\x0c\x12\x16\n\x0enormalizeToken\x18\x03 \x01(\x08\x12\x19\n\x11normalizeSentence\x18\x04 \x01(\x08\x12\x12\n\nreturnSpan\x18\x05 \x01(\x08\x12\x10\n\x08timeZone\x18\x06 \x01(\t\x12\x10\n\x08language\x18\x07 \x01(\t"x\n\x15NERPredictionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12&\n\rprobabilities\x18\x03 \x03(\x0b\x32\x0f.NERPredictions\x12\x17\n\x0fnormalizedValue\x18\x04 \x01(\t"t\n\x0eNERPredictions\x12\r\n\x05label\x18\x01 \x01(\t\x12\x13\n\x0bprobability\x18\x02 \x01(\x02\x12\r\n\x05token\x18\x03 \x01(\t\x12\x17\n\x0fnormalizedValue\x18\x04 \x01(\t\x12\x16\n\x04span\x18\x05 \x01(\x0b\x32\x08.NerSpan"%\n\x07NerSpan\x12\r\n\x05start\x18\x01 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x05\x32Q\n\x13NERPredictorService\x12:\n\x07predict\x12\x15.NERPredictionRequest\x1a\x16.NERPredictionResponse"\x00\x62\x06proto3'
    ),
)


_NERPREDICTIONREQUEST = _descriptor.Descriptor(
    name="NERPredictionRequest",
    full_name="NERPredictionRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="model_id",
            full_name="NERPredictionRequest.model_id",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="document",
            full_name="NERPredictionRequest.document",
            index=1,
            number=2,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b(""),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="normalizeToken",
            full_name="NERPredictionRequest.normalizeToken",
            index=2,
            number=3,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="normalizeSentence",
            full_name="NERPredictionRequest.normalizeSentence",
            index=3,
            number=4,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="returnSpan",
            full_name="NERPredictionRequest.returnSpan",
            index=4,
            number=5,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="timeZone",
            full_name="NERPredictionRequest.timeZone",
            index=5,
            number=6,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="language",
            full_name="NERPredictionRequest.language",
            index=6,
            number=7,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=14,
    serialized_end=179,
)


_NERPREDICTIONRESPONSE = _descriptor.Descriptor(
    name="NERPredictionResponse",
    full_name="NERPredictionResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="success",
            full_name="NERPredictionResponse.success",
            index=0,
            number=1,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="error",
            full_name="NERPredictionResponse.error",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="probabilities",
            full_name="NERPredictionResponse.probabilities",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="normalizedValue",
            full_name="NERPredictionResponse.normalizedValue",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=181,
    serialized_end=301,
)


_NERPREDICTIONS = _descriptor.Descriptor(
    name="NERPredictions",
    full_name="NERPredictions",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="label",
            full_name="NERPredictions.label",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="probability",
            full_name="NERPredictions.probability",
            index=1,
            number=2,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="token",
            full_name="NERPredictions.token",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="normalizedValue",
            full_name="NERPredictions.normalizedValue",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="span",
            full_name="NERPredictions.span",
            index=4,
            number=5,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=303,
    serialized_end=419,
)


_NERSPAN = _descriptor.Descriptor(
    name="NerSpan",
    full_name="NerSpan",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="start",
            full_name="NerSpan.start",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="end",
            full_name="NerSpan.end",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=421,
    serialized_end=458,
)

_NERPREDICTIONRESPONSE.fields_by_name["probabilities"].message_type = _NERPREDICTIONS
_NERPREDICTIONS.fields_by_name["span"].message_type = _NERSPAN
DESCRIPTOR.message_types_by_name["NERPredictionRequest"] = _NERPREDICTIONREQUEST
DESCRIPTOR.message_types_by_name["NERPredictionResponse"] = _NERPREDICTIONRESPONSE
DESCRIPTOR.message_types_by_name["NERPredictions"] = _NERPREDICTIONS
DESCRIPTOR.message_types_by_name["NerSpan"] = _NERSPAN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NERPredictionRequest = _reflection.GeneratedProtocolMessageType(
    "NERPredictionRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _NERPREDICTIONREQUEST,
        "__module__": "ner_pb2"
        # @@protoc_insertion_point(class_scope:NERPredictionRequest)
    },
)
_sym_db.RegisterMessage(NERPredictionRequest)

NERPredictionResponse = _reflection.GeneratedProtocolMessageType(
    "NERPredictionResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _NERPREDICTIONRESPONSE,
        "__module__": "ner_pb2"
        # @@protoc_insertion_point(class_scope:NERPredictionResponse)
    },
)
_sym_db.RegisterMessage(NERPredictionResponse)

NERPredictions = _reflection.GeneratedProtocolMessageType(
    "NERPredictions",
    (_message.Message,),
    {
        "DESCRIPTOR": _NERPREDICTIONS,
        "__module__": "ner_pb2"
        # @@protoc_insertion_point(class_scope:NERPredictions)
    },
)
_sym_db.RegisterMessage(NERPredictions)

NerSpan = _reflection.GeneratedProtocolMessageType(
    "NerSpan",
    (_message.Message,),
    {
        "DESCRIPTOR": _NERSPAN,
        "__module__": "ner_pb2"
        # @@protoc_insertion_point(class_scope:NerSpan)
    },
)
_sym_db.RegisterMessage(NerSpan)


_NERPREDICTORSERVICE = _descriptor.ServiceDescriptor(
    name="NERPredictorService",
    full_name="NERPredictorService",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=460,
    serialized_end=541,
    methods=[
        _descriptor.MethodDescriptor(
            name="predict",
            full_name="NERPredictorService.predict",
            index=0,
            containing_service=None,
            input_type=_NERPREDICTIONREQUEST,
            output_type=_NERPREDICTIONRESPONSE,
            serialized_options=None,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_NERPREDICTORSERVICE)

DESCRIPTOR.services_by_name["NERPredictorService"] = _NERPREDICTORSERVICE

# @@protoc_insertion_point(module_scope)
