# Copyright (c) 2020, salesforce.com, inc.
# All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
# For full license text, see the LICENSE file in the repo root
# or https://opensource.org/licenses/BSD-3-Clause

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: intent.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="intent.proto",
    package="",
    syntax="proto3",
    serialized_options=None,
    serialized_pb=_b(
        '\n\x0cintent.proto"G\n\x16IntentDetectionRequest\x12\x10\n\x08\x64ocument\x18\x01 \x01(\t\x12\x1b\n\x05tasks\x18\x02 \x03(\x0b\x32\x0c.IntentClass"-\n\x0bIntentClass\x12\r\n\x05label\x18\x01 \x01(\t\x12\x0f\n\x07samples\x18\x02 \x03(\t"6\n\x17IntentDetectionResponse\x12\x1b\n\x07results\x18\x01 \x01(\x0b\x32\n.IntentRes"N\n\tIntentRes\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05label\x18\x02 \x01(\t\x12\x13\n\x0bprobability\x18\x03 \x01(\x02\x12\x0c\n\x04sent\x18\x04 \x01(\t2`\n\x16IntentDetectionService\x12\x46\n\x0fIntentDetection\x12\x17.IntentDetectionRequest\x1a\x18.IntentDetectionResponse"\x00\x62\x06proto3'
    ),
)


_INTENTDETECTIONREQUEST = _descriptor.Descriptor(
    name="IntentDetectionRequest",
    full_name="IntentDetectionRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="document",
            full_name="IntentDetectionRequest.document",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="tasks",
            full_name="IntentDetectionRequest.tasks",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=16,
    serialized_end=87,
)


_INTENTCLASS = _descriptor.Descriptor(
    name="IntentClass",
    full_name="IntentClass",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="label",
            full_name="IntentClass.label",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="samples",
            full_name="IntentClass.samples",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=89,
    serialized_end=134,
)


_INTENTDETECTIONRESPONSE = _descriptor.Descriptor(
    name="IntentDetectionResponse",
    full_name="IntentDetectionResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="results",
            full_name="IntentDetectionResponse.results",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=136,
    serialized_end=190,
)


_INTENTRES = _descriptor.Descriptor(
    name="IntentRes",
    full_name="IntentRes",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="success",
            full_name="IntentRes.success",
            index=0,
            number=1,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="label",
            full_name="IntentRes.label",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="probability",
            full_name="IntentRes.probability",
            index=2,
            number=3,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="sent",
            full_name="IntentRes.sent",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=192,
    serialized_end=270,
)

_INTENTDETECTIONREQUEST.fields_by_name["tasks"].message_type = _INTENTCLASS
_INTENTDETECTIONRESPONSE.fields_by_name["results"].message_type = _INTENTRES
DESCRIPTOR.message_types_by_name["IntentDetectionRequest"] = _INTENTDETECTIONREQUEST
DESCRIPTOR.message_types_by_name["IntentClass"] = _INTENTCLASS
DESCRIPTOR.message_types_by_name["IntentDetectionResponse"] = _INTENTDETECTIONRESPONSE
DESCRIPTOR.message_types_by_name["IntentRes"] = _INTENTRES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IntentDetectionRequest = _reflection.GeneratedProtocolMessageType(
    "IntentDetectionRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _INTENTDETECTIONREQUEST,
        "__module__": "intent_pb2"
        # @@protoc_insertion_point(class_scope:IntentDetectionRequest)
    },
)
_sym_db.RegisterMessage(IntentDetectionRequest)

IntentClass = _reflection.GeneratedProtocolMessageType(
    "IntentClass",
    (_message.Message,),
    {
        "DESCRIPTOR": _INTENTCLASS,
        "__module__": "intent_pb2"
        # @@protoc_insertion_point(class_scope:IntentClass)
    },
)
_sym_db.RegisterMessage(IntentClass)

IntentDetectionResponse = _reflection.GeneratedProtocolMessageType(
    "IntentDetectionResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _INTENTDETECTIONRESPONSE,
        "__module__": "intent_pb2"
        # @@protoc_insertion_point(class_scope:IntentDetectionResponse)
    },
)
_sym_db.RegisterMessage(IntentDetectionResponse)

IntentRes = _reflection.GeneratedProtocolMessageType(
    "IntentRes",
    (_message.Message,),
    {
        "DESCRIPTOR": _INTENTRES,
        "__module__": "intent_pb2"
        # @@protoc_insertion_point(class_scope:IntentRes)
    },
)
_sym_db.RegisterMessage(IntentRes)


_INTENTDETECTIONSERVICE = _descriptor.ServiceDescriptor(
    name="IntentDetectionService",
    full_name="IntentDetectionService",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=272,
    serialized_end=368,
    methods=[
        _descriptor.MethodDescriptor(
            name="IntentDetection",
            full_name="IntentDetectionService.IntentDetection",
            index=0,
            containing_service=None,
            input_type=_INTENTDETECTIONREQUEST,
            output_type=_INTENTDETECTIONRESPONSE,
            serialized_options=None,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_INTENTDETECTIONSERVICE)

DESCRIPTOR.services_by_name["IntentDetectionService"] = _INTENTDETECTIONSERVICE

# @@protoc_insertion_point(module_scope)
